services:

  ##### migration runner (run once)
  migrate:
    build: .
    command: ["php", "CLI/Migrate.php"]
    volumes:
      - status-data:/var/lib/aux-status
    environment:
      CONFIG: /etc/aux-status/config.docker.yaml
    configs:
      - source: aux-status-config
        target: /etc/aux-status/config.docker.yaml
    restart: "no"

  ##### php
  php:
    build: .
    depends_on:
      migrate:
        condition: service_completed_successfully
    volumes:
      - status-data:/var/lib/aux-status
    environment:
      CONFIG: /etc/aux-status/config.docker.yaml
    configs:
      - source: aux-status-config
        target: /etc/aux-status/config.docker.yaml
    restart: unless-stopped

  ##### public stuff
  web:
    image: nginx:1.29-alpine
    depends_on:
      - php
    volumes:
      # Nginx only needs the public directory.
      - ./Public:/var/www/html/Public:ro

      # Custom virtual-host configuration.
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    restart: unless-stopped

  ##### poller
  poller:
    build: .
    depends_on:
      migrate:
        condition: service_completed_successfully
    volumes:
      - status-data:/var/lib/aux-status
    environment:
      CONFIG: /etc/aux-status/config.docker.yaml
    configs:
      - source: aux-status-config
        target: /etc/aux-status/config.docker.yaml
    command: ["php", "CronJobs/Poller.php"]
    restart: unless-stopped

configs:
  aux-status-config:
    file: ./docker/config.docker.yaml

volumes:
  status-data:
